name: Install Python2 Package daemonpy
on:
  push:
    branches: [ master ]
    paths:
      - 'daemonpy/**'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'setup.py'
  pull_request:
    branches: [ master ]
    paths:
      - 'daemonpy/**'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'setup.py'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '2.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build
        pip install setuptools wheel
        pip install -r requirements.txt
    - name: Build by python build
      run: |
        python -m build
    - name: Build by setup.py
      run: |
        python setup.py sdist bdist_wheel
